# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec52b165f52b3bed8f4f6c9d10324fbb50b05f4335c5935219f422ada51a9dc0b78ead7681b1ae199714317f2b4742bf007ba0fcbe1f0ce5c8d85c6bd0ae20d

test:
  secret_key_base: 1418bfa1d1a191799a64f598f6cbf51c524497ac8015362962aa4117edf990140551b547c1fbab77f24dd31950c7e759eda6074a05213ee332eaa5052e8a2f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
