# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

# CartoDB OneClick Service https://cartodb.com/open-in-cartodb/
CARTODB_ONECLICK_LINK: 'http://oneclick.cartodb.com/'

# Download path can be configured using this setting
#DOWNLOAD_PATH: "./tmp/cache/downloads"

#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# Institution deployed at
INSTITUTION: 'NYU'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'


PROXY_URL: 'http://ezproxy.library.nyu.edu:2048/login?url=http://maps-restricted.nyusdr.net'
RESTRICTED_URL: 'http://maps-restricted.nyusdr.net/geoserver/wms'

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 15

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'wfs'

# WMS Parameters
WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'
